### ISSUE TITLE
运行Auto-tune报错：  IndexErro

### ISSUE THREAD

**Issue by xing-ye** [FlagOpen/FlagScale#316]
我尝试在NV单节点上测试AutoTune对llama7b模型的策略推荐时，第一个策略运行一段时间后出现了`[2025-01-21 03:18:49,054][FlagScale-AutoTuner][INFO] - task_1 error: {'[default1]:IndexError: index 1 is out of range\n', '[default0]:IndexError: index 1 is out of range\n'}`的报错，请问该如何排查以及可能哪里出现了问题呢。
这是我的脚本 **config_auto_tuner.yaml**
```
defaults:
  - train: demo
  - _self_

experiment:
  exp_name: aquila2
  exp_dir: ./outputs
  task:
    type: train
    backend: megatron
    entrypoint: ./flagscale/train/train_aquila.py
  runner:
    backend: torchrun
    nnodes: 1 
    nproc_per_node: 8 
  envs:
    CUDA_VISIBLE_DEVICES: 0,1,2,3,4,5,6,7
    CUDA_DEVICE_MAX_CONNECTIONS: 1
  auto_tuner:
    space:
      data_parallel_size: "auto"
      use_distributed_optimizer: [true, false]
      tensor_model_parallel_size: [2, 4, 8]
      sequence_parallel: [true]
      pipeline_model_parallel_size: "auto"
      num_layers_per_virtual_pipeline_stage: [1]
      context_parallel_size: "auto"
      expert_model_parallel_size: [1]
      micro_batch_size: "auto"
      use_recompute: [true]
      recompute_method: "auto"
      recompute_granularity: "auto"
      recompute_num_layers: "auto"
    control:
      max_time_per_task: 300
      train_iters: 5
      max_time: 600

action: auto_tune

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra 

train:
  data:
    data_path: /data2/nfs/llama-dataset/merged-1t/merged-1t
```
demo.yaml
```
system:
  tensor_model_parallel_size: 1
  pipeline_model_parallel_size: 1
  disable_bias_linear: True
  use_flash_attn: True
  sequence_parallel: True
  use_distributed_optimizer: True
  precision:
    fp16: True
    initial_loss_scale: 16384
    min_loss_scale: 1.0
  logging:
    log_interval: 1
    tensorboard_log_interval: 1
    wandb_project: "train-llama-7B" 
    wandb_exp_name: "train-test-7B" 
  checkpoint:
    save_interval: 1000

model:
  use_mcore_models: True
  transformer_impl: transformer_engine
  num_layers: 32  
  hidden_size: 4096 
  ffn_hidden_size: 28672
  num_attention_heads: 32 
  seq_length: 2048   
  group_query_attention: False
  num_query_groups: 8
  max_position_embeddings: 4096
  norm_epsilon: 1e-5
  use_rotary_position_embeddings: True
  no_position_embedding: True
  swiglu: True
  multiple_of: 256
  normalization: RMSNorm
  rotary_interleaved_patch: True
  untie_embeddings_and_output_weights: True
  init_method_std: 0.02
  attention_dropout: 0.0
  hidden_dropout: 0.0
  weight_decay: 0.1
  clip_grad: 1.0
  micro_batch_size: 1
  global_batch_size: 32

  optimizer:
    weight_decay: 1e-2
    adam_beta1: 0.9
    adam_beta2: 0.95
    lr_scheduler:
      lr: 0.00015
      min_lr: 1.0e-5
      lr_warmup_fraction: .01
      lr_decay_iters: 1
      lr_decay_style: cosine

data:
  data_path: ${data_path:??}
  split: 1
  tokenizer:
    tokenizer_type: Llama2Tokenizer
    tokenizer_model: /data2/nfs/llama-dataset/tokenizer.model
    vocab_size: 32000
```
